name: "JobSummaries"
on: push

permissions:
  id-token: write
  contents: read


env:
  JFROG_CLI_LOG_LEVEL: DEBUG

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://ecosysjfrog.jfrog.io/
          JF_ACCESS_TOKEN: ${{ secrets.JF_ECO_ACCESS_TOKEN }}
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_PROJECT: jobsummary

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Npm build
        run: |
          cd npm-example
          jf npm-config --repo-resolve=robi-npm --repo-deploy=robi-npm
          jf npm i
          jf npm publish

      - name: Publish build info
        run: |
          jf rt bce
          jf rt bp
      - name: Scan build info
        run: |
          jf bs --fail=false --vuln