name: "JobSummaries"
on: push

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JFrog CLI
        uses: eyaldelarea/setup-jfrog-cli@improve_summary_ui
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_PROJECT: jobsummary
        with:
          download-repository: generic-local-eyal
          version: 2.63.2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          cd docker-oci-examples/fat-manifest-example
          echo ${{ secrets.JF_PASSWORD }} | docker login ${{ vars.JF_URL }} -u ${{ secrets.JF_USER }} --password-stdin
          docker buildx install
          docker buildx create --use --name mybuilder --driver docker-container
          docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 --tag=ecosysjfrog.jfrog.io/docker-local/multi-lini:2 -f=Dockerfile.Fatmanifest --metadata-file=build-metadata --push .
          jf rt build-docker-create docker-local --image-file build-metadata
          docker buildx uninstall
      - name: Docker Scan
        run: |
          jf docker pull ecosysjfrog.jfrog.io/docker-local/multi-lini:2
          jf docker scan --vuln=true ecosysjfrog.jfrog.io/docker-local/multi-lini:2