name: "JobSummaries"
on: push

permissions:
  id-token: write
  contents: read


env:
  JFROG_CLI_LOG_LEVEL: DEBUG

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://ecosysjfrog.jfrog.io/
          JF_ACCESS_TOKEN: ${{ secrets.JF_ECO_ACCESS_TOKEN }}
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_PROJECT: jobsummary
        with:
          download-repository: generic-local-eyal
          version: 2.63.2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"

      - name: Setup Pipenv
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Package managers versions
        run: |
          jf -v
          mvn -v
          python --version
          pip --version
          wheel version
          pip show setuptools
          echo $VIRTUAL_ENV
          node -v
          npm -v
          go version


      - name: Maven build
        run: |
          cd maven-examples/maven-example
          jf mvnc --repo-deploy-releases=libs-release --repo-deploy-snapshots=libs-snapshot --repo-resolve-releases=libs-release --repo-resolve-snapshots=libs-snapshot
          jf mvn clean install -B

      - name: Pip build
        run: |
          cd python-example/pip-example/
          jf pip-config --repo-resolve=robi-pypi-virtual
          jf pip install . --module=jfrog-python-example
          python setup.py sdist bdist_wheel
          jf rt u dist/ robi-pypi-virtual/ --module=jfrog-python-example

      - name: Npm build
        run: |
          cd npm-example
          jf npm-config --repo-resolve=robi-npm --repo-deploy=robi-npm
          jf npm i
          jf npm publish

      - name: Go build
        run: |
          cd golang-example
          jf go-config --repo-resolve=robi-go --repo-deploy=robi-go
          jf go build
          jf go-publish v1.0.0

      - name: Generic build
        run: |
          cd bash-example
          jf rt u ./deploy-file.sh generic-local-robi/ --module=generic-module

      - name: Publish build info
        run: |
          jf rt bce
          jf rt bp
      - name: Scan build info
        run: |
          jf bs --fail=false --vuln